Challenge
Submit the code on the right to prove that it will not cause any error, and also not do anything.

Given Code:


for i in range(1, 8):
    pass

if True:
    pass

def unfinsished_function():
    pass

for i in range(1, 8):
    break
    print(i)

for i in range(1, 8):
    continue
    print(i)

print("nothing else happened")
